// <auto-generated />
using DossierPDP.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DossierPDP.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20191113153817_SeedCustomerTable")]
    partial class SeedCustomerTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DossierPDP.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CustomerFirstName");

                    b.Property<string>("CustomerLastName");

                    b.Property<string>("Email");

                    b.Property<string>("Telephonenumber");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            CustomerFirstName = "Nick",
                            CustomerLastName = "Foulon",
                            Email = "foulonnick@gmail.com",
                            Telephonenumber = "123456789"
                        },
                        new
                        {
                            CustomerId = 2,
                            CustomerFirstName = "Raf",
                            CustomerLastName = "Gillisjans"
                        },
                        new
                        {
                            CustomerId = 3,
                            CustomerFirstName = "Paul-Henry",
                            CustomerLastName = "Decuvelier"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
